package com.ideacome.logistics.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShellLogisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public ShellLogisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modify_date is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modify_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("modify_date =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("modify_date <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("modify_date >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_date >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("modify_date <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("modify_date <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("modify_date in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("modify_date not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("modify_date between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("modify_date not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andTrackingNoIsNull() {
            addCriterion("tracking_no is null");
            return (Criteria) this;
        }

        public Criteria andTrackingNoIsNotNull() {
            addCriterion("tracking_no is not null");
            return (Criteria) this;
        }

        public Criteria andTrackingNoEqualTo(String value) {
            addCriterion("tracking_no =", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoNotEqualTo(String value) {
            addCriterion("tracking_no <>", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoGreaterThan(String value) {
            addCriterion("tracking_no >", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoGreaterThanOrEqualTo(String value) {
            addCriterion("tracking_no >=", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoLessThan(String value) {
            addCriterion("tracking_no <", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoLessThanOrEqualTo(String value) {
            addCriterion("tracking_no <=", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoLike(String value) {
            addCriterion("tracking_no like", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoNotLike(String value) {
            addCriterion("tracking_no not like", value, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoIn(List<String> values) {
            addCriterion("tracking_no in", values, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoNotIn(List<String> values) {
            addCriterion("tracking_no not in", values, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoBetween(String value1, String value2) {
            addCriterion("tracking_no between", value1, value2, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andTrackingNoNotBetween(String value1, String value2) {
            addCriterion("tracking_no not between", value1, value2, "trackingNo");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeIsNull() {
            addCriterion("delivery_corp_code is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeIsNotNull() {
            addCriterion("delivery_corp_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeEqualTo(String value) {
            addCriterion("delivery_corp_code =", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeNotEqualTo(String value) {
            addCriterion("delivery_corp_code <>", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeGreaterThan(String value) {
            addCriterion("delivery_corp_code >", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_corp_code >=", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeLessThan(String value) {
            addCriterion("delivery_corp_code <", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeLessThanOrEqualTo(String value) {
            addCriterion("delivery_corp_code <=", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeLike(String value) {
            addCriterion("delivery_corp_code like", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeNotLike(String value) {
            addCriterion("delivery_corp_code not like", value, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeIn(List<String> values) {
            addCriterion("delivery_corp_code in", values, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeNotIn(List<String> values) {
            addCriterion("delivery_corp_code not in", values, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeBetween(String value1, String value2) {
            addCriterion("delivery_corp_code between", value1, value2, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andDeliveryCorpCodeNotBetween(String value1, String value2) {
            addCriterion("delivery_corp_code not between", value1, value2, "deliveryCorpCode");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDestNuIsNull() {
            addCriterion("dest_nu is null");
            return (Criteria) this;
        }

        public Criteria andDestNuIsNotNull() {
            addCriterion("dest_nu is not null");
            return (Criteria) this;
        }

        public Criteria andDestNuEqualTo(String value) {
            addCriterion("dest_nu =", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuNotEqualTo(String value) {
            addCriterion("dest_nu <>", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuGreaterThan(String value) {
            addCriterion("dest_nu >", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuGreaterThanOrEqualTo(String value) {
            addCriterion("dest_nu >=", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuLessThan(String value) {
            addCriterion("dest_nu <", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuLessThanOrEqualTo(String value) {
            addCriterion("dest_nu <=", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuLike(String value) {
            addCriterion("dest_nu like", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuNotLike(String value) {
            addCriterion("dest_nu not like", value, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuIn(List<String> values) {
            addCriterion("dest_nu in", values, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuNotIn(List<String> values) {
            addCriterion("dest_nu not in", values, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuBetween(String value1, String value2) {
            addCriterion("dest_nu between", value1, value2, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestNuNotBetween(String value1, String value2) {
            addCriterion("dest_nu not between", value1, value2, "destNu");
            return (Criteria) this;
        }

        public Criteria andDestComIsNull() {
            addCriterion("dest_com is null");
            return (Criteria) this;
        }

        public Criteria andDestComIsNotNull() {
            addCriterion("dest_com is not null");
            return (Criteria) this;
        }

        public Criteria andDestComEqualTo(String value) {
            addCriterion("dest_com =", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComNotEqualTo(String value) {
            addCriterion("dest_com <>", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComGreaterThan(String value) {
            addCriterion("dest_com >", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComGreaterThanOrEqualTo(String value) {
            addCriterion("dest_com >=", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComLessThan(String value) {
            addCriterion("dest_com <", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComLessThanOrEqualTo(String value) {
            addCriterion("dest_com <=", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComLike(String value) {
            addCriterion("dest_com like", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComNotLike(String value) {
            addCriterion("dest_com not like", value, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComIn(List<String> values) {
            addCriterion("dest_com in", values, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComNotIn(List<String> values) {
            addCriterion("dest_com not in", values, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComBetween(String value1, String value2) {
            addCriterion("dest_com between", value1, value2, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestComNotBetween(String value1, String value2) {
            addCriterion("dest_com not between", value1, value2, "destCom");
            return (Criteria) this;
        }

        public Criteria andDestStateIsNull() {
            addCriterion("dest_state is null");
            return (Criteria) this;
        }

        public Criteria andDestStateIsNotNull() {
            addCriterion("dest_state is not null");
            return (Criteria) this;
        }

        public Criteria andDestStateEqualTo(Integer value) {
            addCriterion("dest_state =", value, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateNotEqualTo(Integer value) {
            addCriterion("dest_state <>", value, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateGreaterThan(Integer value) {
            addCriterion("dest_state >", value, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("dest_state >=", value, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateLessThan(Integer value) {
            addCriterion("dest_state <", value, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateLessThanOrEqualTo(Integer value) {
            addCriterion("dest_state <=", value, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateIn(List<Integer> values) {
            addCriterion("dest_state in", values, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateNotIn(List<Integer> values) {
            addCriterion("dest_state not in", values, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateBetween(Integer value1, Integer value2) {
            addCriterion("dest_state between", value1, value2, "destState");
            return (Criteria) this;
        }

        public Criteria andDestStateNotBetween(Integer value1, Integer value2) {
            addCriterion("dest_state not between", value1, value2, "destState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shell_logistics
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 27 14:39:12 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shell_logistics
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}