package com.ideacome.logistics.entity;

public class ShellLogisticsWithBLOBs extends ShellLogistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics.last_context
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    private String lastContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics.dest_context
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    private String destContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics.last_context
     *
     * @return the value of shell_logistics.last_context
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public String getLastContext() {
        return lastContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics.last_context
     *
     * @param lastContext the value for shell_logistics.last_context
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public void setLastContext(String lastContext) {
        this.lastContext = lastContext == null ? null : lastContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics.dest_context
     *
     * @return the value of shell_logistics.dest_context
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public String getDestContext() {
        return destContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics.dest_context
     *
     * @param destContext the value for shell_logistics.dest_context
     *
     * @mbggenerated Mon Mar 27 14:39:12 CST 2017
     */
    public void setDestContext(String destContext) {
        this.destContext = destContext == null ? null : destContext.trim();
    }
}