package com.ideacome.logistics.entity;

import java.io.Serializable;
import java.util.Date;

public class ShellLogisticsSubscription implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.create_date
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.modify_date
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.version
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.order_id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.shipping_id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private Long shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.tracking_no
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private String trackingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.delivery_corp_code
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private String deliveryCorpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.result
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.return_code
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shell_logistics_subscription.message
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.id
     *
     * @return the value of shell_logistics_subscription.id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.id
     *
     * @param id the value for shell_logistics_subscription.id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.create_date
     *
     * @return the value of shell_logistics_subscription.create_date
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.create_date
     *
     * @param createDate the value for shell_logistics_subscription.create_date
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.modify_date
     *
     * @return the value of shell_logistics_subscription.modify_date
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.modify_date
     *
     * @param modifyDate the value for shell_logistics_subscription.modify_date
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.version
     *
     * @return the value of shell_logistics_subscription.version
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.version
     *
     * @param version the value for shell_logistics_subscription.version
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.order_id
     *
     * @return the value of shell_logistics_subscription.order_id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.order_id
     *
     * @param orderId the value for shell_logistics_subscription.order_id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.shipping_id
     *
     * @return the value of shell_logistics_subscription.shipping_id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public Long getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.shipping_id
     *
     * @param shippingId the value for shell_logistics_subscription.shipping_id
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setShippingId(Long shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.tracking_no
     *
     * @return the value of shell_logistics_subscription.tracking_no
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public String getTrackingNo() {
        return trackingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.tracking_no
     *
     * @param trackingNo the value for shell_logistics_subscription.tracking_no
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setTrackingNo(String trackingNo) {
        this.trackingNo = trackingNo == null ? null : trackingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.delivery_corp_code
     *
     * @return the value of shell_logistics_subscription.delivery_corp_code
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public String getDeliveryCorpCode() {
        return deliveryCorpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.delivery_corp_code
     *
     * @param deliveryCorpCode the value for shell_logistics_subscription.delivery_corp_code
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setDeliveryCorpCode(String deliveryCorpCode) {
        this.deliveryCorpCode = deliveryCorpCode == null ? null : deliveryCorpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.result
     *
     * @return the value of shell_logistics_subscription.result
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.result
     *
     * @param result the value for shell_logistics_subscription.result
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.return_code
     *
     * @return the value of shell_logistics_subscription.return_code
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.return_code
     *
     * @param returnCode the value for shell_logistics_subscription.return_code
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shell_logistics_subscription.message
     *
     * @return the value of shell_logistics_subscription.message
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shell_logistics_subscription.message
     *
     * @param message the value for shell_logistics_subscription.message
     *
     * @mbggenerated Mon Mar 27 14:40:40 CST 2017
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}